### ISSUE TITLE
GITHUB API may return bad content, this results in random not checked exceptions:

### ISSUE THREAD

**Issue by baranowb** [jboss-set/pull-request-processor#74] opened 2017-08-16 07:28 UTC
Exception in thread "main" java.lang.NullPointerException
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.pullRequestToPullRequest(GitHubWrapper.java:75)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)

**Comment by soul2zimate** [comment] 2017-08-16 08:44
bad content means empty content? 
It seems same issue as https://github.com/jboss-set/pull-request-processor/issues/69 but with different variable, Do you know which random bad content here? Although I think we should check all possible empty returned value from Github. I think this is an issue from Aphrodite.

**Comment by baranowb** [comment] 2017-08-21 09:35
Not really:
java.lang.Exception: GHPullRequest@5b218417[base=org.kohsuke.github.GHCommitPointer@1caa0244,head=org.kohsuke.github.GHCommitPointer@7ce026d3,additions=0,merged=false,mergeable=<null>,deletions=0,assignee=<null>,state=open,number=2306,comments=0,labels=<null>,title=[JBEAP-11976] Upgrade PicketLink to 2.5.5.SP8,milestone=<null>,url=https://api.github.com/repos/jbossas/jboss-eap7/pulls/2306,id=136464432]
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.pullRequestToPullRequest(GitHubWrapper.java:88)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.toAphroditePullRequests(GitHubWrapper.java:63)
        at org.jboss.set.aphrodite.repository.services.github.GitHubRepositoryService.getPullRequestsByState(GitHubRepositoryService.java:207)
        at org.jboss.set.aphrodite.Aphrodite.getPullRequestsByState(Aphrodite.java:660)
        at org.jboss.set.pull.processor.impl.process.OpenPRProcessor.fetchPullRequestsRaw(OpenPRProcessor.java:69)
        at org.jboss.set.pull.processor.AbstractProcessor.fetchPullRequests(AbstractProcessor.java:82)
        at org.jboss.set.pull.processor.AbstractProcessor.process(AbstractProcessor.java:100)
        at org.jboss.set.pull.processor.Main.start(Main.java:99)
        at org.jboss.set.pull.processor.Main.main(Main.java:170)
Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: -1, message: 'null' for URL: https://api.github.com/repos/jbossas/jboss-eap7/pulls/2306
        at org.kohsuke.github.Requester.parse(Requester.java:540)
        at org.kohsuke.github.Requester._to(Requester.java:251)
        at org.kohsuke.github.Requester.to(Requester.java:220)
        at org.kohsuke.github.GHPullRequest.populate(GHPullRequest.java:205)
        at org.kohsuke.github.GHPullRequest.getMergeable(GHPullRequest.java:170)
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.pullRequestToPullRequest(GitHubWrapper.java:74)
        ... 15 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.kohsuke.github.Requester.parse(Requester.java:514)
        ... 20 more
Aug 21, 2017 11:06:55 AM org.jboss.set.pull.processor.AbstractProcessor log
SEVERE: OpenPRProcessor Failed at: PullRequestReference [pullRequest=null, componentDefinition=StreamComponentDefinition [name=jbossas-jboss-eap7, found=true]]
java.lang.NullPointerException
        at org.jboss.set.pull.processor.AbstractProcessor.lambda$fetchPullRequests$0(AbstractProcessor.java:85)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jboss.set.pull.processor.AbstractProcessor.fetchPullRequests(AbstractProcessor.java:94)
        at org.jboss.set.pull.processor.AbstractProcessor.process(AbstractProcessor.java:100)
        at org.jboss.set.pull.processor.Main.start(Main.java:99)
        at org.jboss.set.pull.processor.Main.main(Main.java:170)


and



java.lang.Exception: GHPullRequest@5e2c3d18[base=org.kohsuke.github.GHCommitPointer@5386659f,head=org.kohsuke.github.GHCommitPointer@14028087,additions=113,merged=false,mergeable=<null>,deletions=25,assignee=<null>,state=open,number=2309,comments=0,labels=<null>,title=[JBEAP-11910] TransactionAttribute annotation is inherited from inter…,milestone=<null>,url=https://api.github.com/repos/jbossas/jboss-eap7/pulls/2309,id=136705945]
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.pullRequestToPullRequest(GitHubWrapper.java:88)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.toAphroditePullRequests(GitHubWrapper.java:63)
        at org.jboss.set.aphrodite.repository.services.github.GitHubRepositoryService.getPullRequestsByState(GitHubRepositoryService.java:207)
        at org.jboss.set.aphrodite.Aphrodite.getPullRequestsByState(Aphrodite.java:660)
        at org.jboss.set.pull.processor.impl.process.OpenPRProcessor.fetchPullRequestsRaw(OpenPRProcessor.java:69)
        at org.jboss.set.pull.processor.AbstractProcessor.fetchPullRequests(AbstractProcessor.java:82)
        at org.jboss.set.pull.processor.AbstractProcessor.process(AbstractProcessor.java:100)
        at org.jboss.set.pull.processor.Main.start(Main.java:99)
        at org.jboss.set.pull.processor.Main.main(Main.java:170)
Caused by: java.lang.NullPointerException
        at org.jboss.set.aphrodite.repository.services.github.GitHubWrapper.pullRequestToPullRequest(GitHubWrapper.java:74)
        ... 15 more

**Comment by baranowb** [comment] 2017-08-21 09:36
Oh, and btw, I made a mistake, this should have been in aphro. @soul2zimate ^^

**Comment by soul2zimate** [comment] 2017-08-21 09:46
If the bad content is caused by connection difficulty, we can then introduce Optional to avoid NPE.

**Comment by soul2zimate** [comment] 2017-08-22 00:49
https://github.com/jboss-set/aphrodite/issues/150

**Comment by baranowb** [comment] 2017-08-22 05:36
Nope, it seems unrelated.

**Comment by soul2zimate** [comment] 2017-11-29 05:05
Fixed in Aphrodite 0.7.4.Final issue https://github.com/jboss-set/aphrodite/issues/150

**Closed by soul2zimate** 2017-11-29 05:05 UTC
